-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 18:50:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nome_categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ginásio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ginásio` (
  `nome_ginasio` VARCHAR(20) NOT NULL,
  `id_ginasio` INT NOT NULL,
  `tipo_ginasio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ginasio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tipo de inscrição`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo de inscrição` (
  `id_tipo` INT NOT NULL,
  `nome_tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membro` (
  `cc_membro` INT NOT NULL,
  `nome_membro` VARCHAR(45) NULL DEFAULT NULL,
  `Ginasio_id_ginasio` INT NOT NULL,
  `peso_membro` DECIMAL(10,0) NULL DEFAULT NULL,
  `altura_membro` DECIMAL(10,0) NULL DEFAULT NULL,
  `localidade_membro` VARCHAR(45) NULL DEFAULT NULL,
  `data_nascimento_membro` DATE NULL DEFAULT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  `tipo de inscrição_id_tipo` INT NOT NULL,
  PRIMARY KEY (`cc_membro`),
  UNIQUE INDEX `cc_Atleta_UNIQUE` (`cc_membro` ASC) VISIBLE,
  INDEX `fk_Atleta_Clube_idx` (`Ginasio_id_ginasio` ASC) VISIBLE,
  INDEX `fk_Atleta_Categoria1_idx` (`Categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_membro_tipo de inscrição1_idx` (`tipo de inscrição_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_Categoria1`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_Atleta_Clube`
    FOREIGN KEY (`Ginasio_id_ginasio`)
    REFERENCES `mydb`.`ginásio` (`id_ginasio`),
  CONSTRAINT `fk_membro_tipo de inscrição1`
    FOREIGN KEY (`tipo de inscrição_id_tipo`)
    REFERENCES `mydb`.`tipo de inscrição` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pt` (
  `id_pt` INT NOT NULL,
  `nome_pt` VARCHAR(45) NULL DEFAULT NULL,
  `ginásio_id_ginasio` INT NOT NULL,
  PRIMARY KEY (`id_pt`),
  INDEX `fk_pt_ginásio1_idx` (`ginásio_id_ginasio` ASC) VISIBLE,
  CONSTRAINT `fk_pt_ginásio1`
    FOREIGN KEY (`ginásio_id_ginasio`)
    REFERENCES `mydb`.`ginásio` (`id_ginasio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aulas` (
  `id_aulas` INT NOT NULL,
  `nome_aulas` VARCHAR(45) NULL DEFAULT NULL,
  `PT_id_pt` INT NOT NULL,
  `PT_Ginásio_id_ginasio` INT NOT NULL,
  `Membro_cc_membro` INT NOT NULL,
  `Membro_Ginasio_id_ginasio` INT NOT NULL,
  `Membro_Categoria_id_categoria` INT NOT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_aulas`),
  INDEX `fk_Aulas_PT1_idx` (`PT_id_pt` ASC, `PT_Ginásio_id_ginasio` ASC) VISIBLE,
  INDEX `fk_Aulas_Membro1_idx` (`Membro_cc_membro` ASC, `Membro_Ginasio_id_ginasio` ASC, `Membro_Categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_Aulas_Categoria1_idx` (`Categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Aulas_Categoria1`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_Aulas_Membro1`
    FOREIGN KEY (`Membro_cc_membro` , `Membro_Ginasio_id_ginasio` , `Membro_Categoria_id_categoria`)
    REFERENCES `mydb`.`membro` (`cc_membro` , `Ginasio_id_ginasio` , `Categoria_id_categoria`),
  CONSTRAINT `fk_Aulas_PT1`
    FOREIGN KEY (`PT_id_pt`)
    REFERENCES `mydb`.`pt` (`id_pt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nutricionista` (
  `id_nutricionista` INT NOT NULL,
  `nome_nutricionista` VARCHAR(45) NULL DEFAULT NULL,
  `Ginásio_id_ginasio` INT NOT NULL,
  PRIMARY KEY (`id_nutricionista`),
  INDEX `fk_Nutricionista_Ginásio1_idx` (`Ginásio_id_ginasio` ASC) VISIBLE,
  CONSTRAINT `fk_Nutricionista_Ginásio1`
    FOREIGN KEY (`Ginásio_id_ginasio`)
    REFERENCES `mydb`.`ginásio` (`id_ginasio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id_consulta` INT NOT NULL,
  `tipo_consulta` VARCHAR(45) NULL DEFAULT NULL,
  `Nutricionista_id_nutricionista` INT NOT NULL,
  `Nutricionista_Ginásio_id_ginasio` INT NOT NULL,
  `Membro_cc_membro` INT NOT NULL,
  `Membro_Ginasio_id_ginasio` INT NOT NULL,
  `Membro_Categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_Consulta_Nutricionista1_idx` (`Nutricionista_id_nutricionista` ASC, `Nutricionista_Ginásio_id_ginasio` ASC) VISIBLE,
  INDEX `fk_Consulta_Membro1_idx` (`Membro_cc_membro` ASC, `Membro_Ginasio_id_ginasio` ASC, `Membro_Categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Membro1`
    FOREIGN KEY (`Membro_cc_membro` , `Membro_Ginasio_id_ginasio` , `Membro_Categoria_id_categoria`)
    REFERENCES `mydb`.`membro` (`cc_membro` , `Ginasio_id_ginasio` , `Categoria_id_categoria`),
  CONSTRAINT `fk_Consulta_Nutricionista1`
    FOREIGN KEY (`Nutricionista_id_nutricionista` , `Nutricionista_Ginásio_id_ginasio`)
    REFERENCES `mydb`.`nutricionista` (`id_nutricionista` , `Ginásio_id_ginasio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `idStaff` INT NOT NULL,
  `nome_staff` VARCHAR(45) NOT NULL,
  `Ginásio_id_ginasio` INT NOT NULL,
  PRIMARY KEY (`idStaff`),
  INDEX `fk_Staff_Ginásio1_idx` (`Ginásio_id_ginasio` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Ginásio1`
    FOREIGN KEY (`Ginásio_id_ginasio`)
    REFERENCES `mydb`.`ginásio` (`id_ginasio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
