-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 20:04:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ginásio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ginásio` (
  `id_ginásio` INT NOT NULL,
  `nome_ginásio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ginásio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo de inscrição`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo de inscrição` (
  `id_tipo` INT NOT NULL,
  `nome_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membro` (
  `id_membro` INT NOT NULL,
  `nome_membro` VARCHAR(45) NULL,
  `peso_membro` DECIMAL NULL,
  `altura_membro` DECIMAL NULL,
  `localidade_membro` VARCHAR(45) NULL,
  `data_nascimento_membro` DATE NULL,
  `tipo de inscrição_id_tipo` INT NOT NULL,
  `ginásio_id_ginásio` INT NOT NULL,
  PRIMARY KEY (`id_membro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pt` (
  `id_pt` INT NOT NULL,
  `nome_pt` VARCHAR(45) NULL,
  `ginásio_id_ginásio` INT NOT NULL,
  PRIMARY KEY (`id_pt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aulas` (
  `id_aulas` INT NOT NULL,
  `nome_aulas` VARCHAR(45) NULL,
  `data_aulas` DATE NULL,
  `pt_id_pt` INT NOT NULL,
  `membro_id_membro` INT NOT NULL,
  PRIMARY KEY (`id_aulas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id_staff` INT NOT NULL,
  `nome_staff` VARCHAR(45) NULL,
  `ginásio_id_ginásio` INT NOT NULL,
  PRIMARY KEY (`id_staff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nutricionista` (
  `id_nutricionista` INT NOT NULL,
  `nome_nutricionista` VARCHAR(45) NULL,
  `ginásio_id_ginásio` INT NOT NULL,
  PRIMARY KEY (`id_nutricionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id_consulta` INT NOT NULL,
  `data_consulta` DATE NULL,
  `tipo_consulta` VARCHAR(45) NULL,
  `membro_id_membro` INT NOT NULL,
  `nutricionista_id_nutricionista` INT NOT NULL,
  PRIMARY KEY (`id_consulta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
